# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)
require 'rake'

# Gets rid of WARNING: Global access to Rake DSL methods is deprecated
include Rake::DSL

BiProjMgmt::Application.load_tasks
